"""Add unique constraint to market data

Revision ID: 9f1ef637b5dc
Revises: 5d3f485fa5f1
Create Date: 2026-08-01 14:43:12.439395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1ef637b5dc'
down_revision: Union[str, Sequence[str], None] = '5d3f485fa5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_market_data_instrument_timestamp', 'market_data', ['instrument_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_market_data_instrument_timestamp', 'market_data', type_='unique')
    # ### end Alembic commands ###
